deploy:
  stage: deploy
  tags:
    - testrunner
  only:
    - main
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
    - |
      ssh -o StrictHostKeyChecking=no root@$DEPLOY_SERVER_IP << 'EOF'
        set -e   
        cd /opt/itec-frontend
        docker compose down
        rm -rf package-lock.json dist node_modules
        git checkout main
        git pull origin main
        npm install
        npm run build
        docker compose up --build -d
      EOF
